Navigation = ["NavigationNon"]
Java = ["JavaNon"]
Matlab = ["MatlabNon"]
Prolog = ["PrologNon"]
Python = ["PythonNon"]
Rust = ["RustNon"]
VHDL = ["VHDLnon"]
EclipseCCR = ["EclipseRule"]
VSCodeCcrRule = ["VSCodeNonCcrRule"]
