_enabled_ordered = ["Alphabet", "Navigation", "NavigationNon", "Numbers", "Punctuation", "Keyboard", "CasterRule", "CasterMicRule", "HardwareRule", "MouseAlternativesRule", "WindowManagementRule", "DouglasGridRule", "RainbowGridRule", "SudokuGridRule", "HMCRule", "HMCConfirmRule", "HMCDirectoryRule", "HMCHistoryRule", "HMCLaunchRule", "HMCSettingsRule", "HistoryRule", "ChainAlias", "Alias", "BringRule", "Again", "GrammarActivatorRule", "HooksActivationRule", "DictationSinkRule"]
_internal = ["GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "ManualGrammarReloadRule"]

[whitelisted]
Alphabet = true
Navigation = true
NavigationNon = true
Numbers = true
Punctuation = true
Keyboard = true
CasterRule = true
CasterMicRule = true
HardwareRule = true
MouseAlternativesRule = true
WindowManagementRule = true
DouglasGridRule = true
RainbowGridRule = true
SudokuGridRule = true
HMCRule = true
HMCConfirmRule = true
HMCDirectoryRule = true
HMCHistoryRule = true
HMCLaunchRule = true
HMCSettingsRule = true
HistoryRule = true
ChainAlias = true
Alias = true
BringRule = true
Again = true
JetbrainsRule = true
TextManipulation = true
DictationSinkRule = true
ExcelRule = true
OutlookRule = true
MSTeamsRule = true
WebexTeamsRule = true
GitterRule = true
LegionGridRule = true
AcrobatRule = true
FoxitRule = true
GitBashRule = true
WindowsSpeechRecognitionRule = true
DragonRule = true
SpellingWindowRule = true
FirefoxRule = true
ChromeRule = true
JiraRule = true
fmanRule = true
SyncDirsRule = true
TotalCommanderRule = true
MSWordRule = true
FileDialogueRule = true
IERule = true
GitHubDeskRule = true
KDiff3Rule = true
SQLDeveloperRule = true
SublimeRule = true
VisualStudioRule = true
UnityRule = true
EmacsRule = true
TyporaRule = true
NPPRule = true
SSMSRule = true
FlashDevelopRule = true
MSVCRule = true
LyxRule = true
AtomRule = true
RStudioRule = true
VSCodeNonCcrRule = true
VSCodeCcrRule = true
EclipseCCR = true
EclipseRule = true
Markdown = true
RustNon = true
Rust = true
CPP = true
SQL = true
Go = true
VHDLnon = true
VHDL = true
PrologNon = true
Prolog = true
Dart = true
VoiceDevCommands = true
LaTeX = true
MatlabNon = true
Matlab = true
Javascript = true
Java = true
JavaNon = true
Rlang = true
PythonNon = true
Python = true
Bash = true
HTML = true
CSharp = true
Haxe = true
CSSTreeRule = true
SikuliRule = true
SikuliManagementRule = true
